services:
  netbox:
    image: localhost/netbox-plugin-dns:latest
    build:
      context: .
      dockerfile: ./netbox.Containerfile
    depends_on:
    - postgres
    - redis
    - redis-cache
    env_file: env/netbox.env
    user: 'unit:root'
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:8080/login/ || exit 1"
    ports:
    - "9999:8080"

  postgres:
    image: docker.io/library/postgres:17
    env_file: env/postgres.env
  
  redis:
    image: docker.io/valkey/valkey:8.0.2
    command:
    - sh
    - -c
    - valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD
    env_file: env/redis.env
  
  redis-cache:
    image: docker.io/valkey/valkey:8.0.2
    command:
    - sh
    - -c
    - valkey-server --requirepass $$REDIS_PASSWORD
    env_file: env/redis-cache.env
